version: "3.7"

services:
  vikranportfolio:
    image: nginx:1.21.0-alpine
    volumes: 
      - .:/usr/share/nginx/html/
    ports:
      - "8080:80"
    networks:
      - proxy
    labels: 
      - traefik.enable=true
      - traefik.http.routers.vikranportfolio-http.rule=Host(`test.localhost`)
      - traefik.http.routers.vikranportfolio-http.entrypoints=http
      # - traefik.http.routers.vikranportfolio.middlewares=redirect
      # - traefik.http.routers.vikranportfolio-secure.rule=Host(`hunvikran.com`)
      # - traefik.http.routers.vikranportfolio-secure.entrypoints=https
      # - traefik.http.routers.vikranportfolio-secure.tls=true
      # - traefik.http.routers.vikranportfolio-secure.tls.certresolver=letsencrypt
      - traefik.http.services.vikranportfolio.loadbalancer.server.port=80
      # - traefik.http.middlewares.redirect.redirectscheme.scheme=https

networks:
  proxy:
    external: true