version: "3.7"

services:
  vikranportfolio:
    image: nginx:1.21.0-alpine
    volumes:
      - .:/usr/share/nginx/html/
    ports:
      - "3000:80"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.vikranportfolio-http.rule=Host(`hunvikran.com`)
      - traefik.http.routers.vikranportfolio-http.entrypoints=http
      - traefik.http.routers.vikranportfolio-http.middlewares=redirect
      - traefik.http.routers.vikranportfolio-https.rule=Host(`hunvikran.com`)
      - traefik.http.routers.vikranportfolio-https.entrypoints=https
      - traefik.http.routers.vikranportfolio-https.tls=true
      - traefik.http.routers.vikranportfolio-https.tls.certresolver=letsencrypt
      - traefik.http.services.vikranportfolio.loadbalancer.server.port=80
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https

networks:
  proxy:
    external: true